import os
from slack_sdk.web.async_client import AsyncWebClient
from slack_sdk.errors import SlackApiError


def _build_blocks(state: dict) -> list:
    runbook        = state.get("runbook", {})
    alert_name     = state.get("alert_name", "Unknown Alert")
    severity       = state.get("severity", "UNKNOWN").upper()
    confidence     = state.get("confidence_score", 0.0)
    root_cause     = runbook.get("root_cause_explanation", "No root cause identified.")
    prevention     = runbook.get("prevention", "No prevention strategy provided.")
    triage_note    = runbook.get("triage_note", "AI Swarm has completed initial triage and generated a runbook draft.")
    steps: list    = runbook.get("immediate_steps", [])
    top_4_steps    = steps[:4] if steps else ["No steps available."]

    # Confidence color indicator
    confidence_pct = round(confidence * 100)
    if confidence_pct >= 80:
        confidence_indicator = f"{confidence_pct}% 🟢"
    elif confidence_pct >= 60:
        confidence_indicator = f"{confidence_pct}% 🟡"
    else:
        confidence_indicator = f"{confidence_pct}% 🔴"

    # Severity emoji
    severity_emoji = {"P1": "🔴", "P2": "🟠", "P3": "🟡"}.get(severity, "⚪")

    # Numbered steps as a single string
    steps_text = "\n".join(
        f"{i + 1}. {step}" for i, step in enumerate(top_4_steps)
    )

    return [
        # Header
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🚨 Incident Detected — {alert_name}",
                "emoji": True,
            },
        },
        # Divider
        {"type": "divider"},
        # Severity + confidence side by side
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Severity*\n{severity_emoji} {severity}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Confidence*\n{confidence_indicator}",
                },
            ],
        },
        # Triage Note
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Triage Note*\n{triage_note}",
            },
        },
        # Root cause
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Root Cause*\n{root_cause}",
            },
        },
        # Immediate steps
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Immediate Steps*\n{steps_text}",
            },
        },
        # Prevention
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Prevention*\n{prevention}",
            },
        },
        # Divider
        {"type": "divider"},
        # Footer context
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        f"Service: *{state.get('service', 'unknown')}* "
                        f"| Incident ID: `{state.get('incident_id', 'N/A')}` "
                        f"| Generated by *Incident Autopilot*"
                    ),
                }
            ],
        },
    ]

async def send_status_update_notification(payload: dict) -> None:
    token      = os.getenv("SLACK_BOT_TOKEN")
    channel_id = os.getenv("SLACK_CHANNEL_ID")

    if not token or not channel_id:
        return

    client = AsyncWebClient(token=token)
    
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"✅ Incident {payload.get('status', 'CLOSED')} — {payload.get('alert_name', 'Unknown Alert')}",
                "emoji": True,
            },
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Resolution Note*\n{payload.get('resolution_note', 'No note provided.')}",
            },
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Incident ID: `{payload.get('incident_id', 'N/A')}` | Notified by *Incident Autopilot*",
                }
            ],
        },
    ]

    try:
        await client.chat_postMessage(
            channel=channel_id,
            text=f"✅ Incident Closed: {payload.get('alert_name', 'Unknown')}",
            blocks=blocks,
        )
    except Exception as e:
        print(f"[send_status_update_notification] ERROR: {e}")


async def send_incident_notification(state: dict) -> None:
    """
    Posts a structured Block Kit incident message to the configured Slack channel.
    Raises SlackApiError on API-level failures (caller should catch).
    """
    token      = os.getenv("SLACK_BOT_TOKEN")
    channel_id = os.getenv("SLACK_CHANNEL_ID")

    if not token or not channel_id:
        raise EnvironmentError(
            "SLACK_BOT_TOKEN and SLACK_CHANNEL_ID must be set in .env"
        )

    client = AsyncWebClient(token=token)
    blocks = _build_blocks(state)

    await client.chat_postMessage(
        channel=channel_id,
        text=f"🚨 Incident: {state.get('alert_name', 'Unknown')} — {state.get('severity', '')}",  # fallback for notifications
        blocks=blocks,
    )